### ISSUE TITLE
Nested Attributes Always require to include i18n::Alchemy

### ISSUE THREAD

**Issue by lexrupy** [carlosantoniodasilva/i18n_alchemy#26]
When you have a model using i18n_alchemy, and have some nested association with accepts_nested_attributes, the nested is required to include i18n_alchemy, that is not desired.

**Comment by sobrinho** [comment]
@juarezlustosa please research on that.

**Comment by JuarezLustosa** [comment]
@carlosantoniodasilva You can close this issue. I tested here and can't reproduce this error. It is fixed.

**Comment by carlosantoniodasilva** [comment]
Thanks!
