### ISSUE TITLE
Can't install on Rails 4.2.0

### ISSUE THREAD

**Issue by alexandreviegas** [carlosantoniodasilva/i18n_alchemy#34]
Hi, I tried to use with rails 4.2.0 but on 'bundle install':
$ bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    i18n_alchemy (>= 0) ruby depends on
      activesupport (~> 3.0) ruby

    rails (= 4.2.0) ruby depends on
      activesupport (4.2.0)

**Comment by carlosantoniodasilva** [comment]
It doesn't say which i18n alchemy version it's getting, can you tell me?

It should be fine to use master though, which has the green test suite for Rails 4.2: https://github.com/carlosantoniodasilva/i18n_alchemy/compare/v0.2.1...master

If that works for you I can push up a new version. Thanks!

**Comment by alexandreviegas** [comment]
Sorry about that.
Actually, I tried on Gemfile without specify a version, just: gem 'i18n_alchemy'
When using version: gem 'i18n_alchemy', '0.2.1' 
---------------------------------------------------------------------------------------------
$ bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (4.2.0)

  In Gemfile:
    i18n_alchemy (= 0.2.1) ruby depends on
      activesupport (< 4.2, >= 3.2.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
---------------------------------------------------------------------------------------------

Then, after 'bundle update':
---------------------------------------------------------------------------------------------
$ bundle update
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    i18n_alchemy (= 0.2.1) ruby depends on
      activesupport (< 4.2, >= 3.2.0) ruby

    rails (= 4.2.0) ruby depends on
      activesupport (4.2.0)
---------------------------------------------------------------------------------------------

**Comment by alexandreviegas** [comment]
It works with: 
gem 'i18n_alchemy', :git => 'https://github.com/carlosantoniodasilva/i18n_alchemy.git', :branch => 'master'

**Comment by carlosantoniodasilva** [comment]
Awesome, so if it is all good I will push a new version soon. Thanks for testing it!
